// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOjY_8QDS6TeOONSw1X-55XbIHqGNGzc',
    appId: '1:506307194939:web:4d0aedfccf89a048d66c1e',
    messagingSenderId: '506307194939',
    projectId: 'crud-f7da6',
    authDomain: 'crud-f7da6.firebaseapp.com',
    storageBucket: 'crud-f7da6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB07rAIz52XPvmkvgEsv8lE_od2iuNg2YQ',
    appId: '1:506307194939:android:f7043427008c9748d66c1e',
    messagingSenderId: '506307194939',
    projectId: 'crud-f7da6',
    storageBucket: 'crud-f7da6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1accPXXPpTxcUPYzrAnKQphQI8IIFSpg',
    appId: '1:506307194939:ios:6b0fd0381d9e4726d66c1e',
    messagingSenderId: '506307194939',
    projectId: 'crud-f7da6',
    storageBucket: 'crud-f7da6.firebasestorage.app',
    iosBundleId: 'com.example.collegeCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1accPXXPpTxcUPYzrAnKQphQI8IIFSpg',
    appId: '1:506307194939:ios:6b0fd0381d9e4726d66c1e',
    messagingSenderId: '506307194939',
    projectId: 'crud-f7da6',
    storageBucket: 'crud-f7da6.firebasestorage.app',
    iosBundleId: 'com.example.collegeCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJOjY_8QDS6TeOONSw1X-55XbIHqGNGzc',
    appId: '1:506307194939:web:799de7afac7141dfd66c1e',
    messagingSenderId: '506307194939',
    projectId: 'crud-f7da6',
    authDomain: 'crud-f7da6.firebaseapp.com',
    storageBucket: 'crud-f7da6.firebasestorage.app',
  );
}
